### ISSUE TITLE
Atividades

### ISSUE THREAD

**Issue by felipefreitassilva** [LuHellerKP/Trabalho-T1-Gerenciamento-Configura-o-PUCRS#7]
- [x] #1 
- [x] #6 
- [x] #13
- [x] #12
- [x] #11
- [x] #9
- [x] #8

**Comment by LuHellerKP** [comment]
Trabalho finalizado,
Vídeo de explicação disponível em:
https://www.youtube.com/watch?v=aQ2Ig08eMBo
